image: docker:stable

stages:
  - build
  - deploy

include:
- project: 'milobella/devops/ci-templates'
  ref: master
  file: '/templates/Milobella-Docker.gitlab-ci.yml'

#.milobella_docker_deploy: &milobella_docker_deploy
#  stage: deploy
#  script:
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#    - docker push $CI_REGISTRY_IMAGE:$(cat VERSION.txt)

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build_image:
  <<: *milobella_docker_build
  variables:
    MODULE_DESCRIPTION = "Http server which is the main and only entry point of Milobella."
  stage: build

#deploy_image:
#  stage: deploy
#  script:
#
#    - sh scripts/docker_push.sh
