image: docker:stable

before_script:
  - docker info

build_image:
  script:
    - export VERSION=$(cat VERSION.txt)
    - docker build -t milobella/oratio:$VERSION
      --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      --build-arg VCS_REF=master
      --build-arg BUILD_VERSION=$VERSION
      .
  tags: [docker,milobella]
