image: docker:stable

stages:
  - build
  - release

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  variables:
    PROJECT_NAME: "milobella"
    MODULE_NAME: ${CI_PROJECT_NAME}
    GITLAB_HOST: "gitlab.milobella.com"
    MODULE_DESCRIPTION: "Http server which is the main and only entry point of Milobella."
  script:
  # Write the id_rsa private key into the good path
  - mkdir -p private && echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private/id_rsa
  - docker build -t $CONTAINER_TEST_IMAGE --add-host ${GITLAB_HOST}:192.168.1.15
    --build-arg BUILD_VERSION=$(cat VERSION.txt)
    --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    --build-arg GITLAB_HOST=${GITLAB_HOST}
    --build-arg PROJECT_NAME=${PROJECT_NAME}
    --build-arg MODULE_NAME=${MODULE_NAME}
    --build-arg MODULE_DESCRIPTION=${MODULE_DESCRIPTION}
    --build-arg VCS_REF=master
    --build-arg SSH_RSA_KEY=private/id_rsa
    .
  - docker push $CONTAINER_TEST_IMAGE
  tags: [docker,milobella]

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_LATEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CI_REGISTRY_IMAGE:$(cat VERSION.txt)
    - docker push $CONTAINER_LATEST_IMAGE
    - docker push $CI_REGISTRY_IMAGE:$(cat VERSION.txt)
  tags: [docker,milobella]
  only: [master]

