[server]
port = 9100
log_level = 5

[tracing]
service_name = "milobella"
jaeger_agent_hostname = "0.0.0.0"
jaeger_agent_port = 6783

[cerebro]
host = "0.0.0.0"
port = 9444
understand_endpoint = "/understand"

[anima]
host = "0.0.0.0"
port = 9333
restitute_endpoint = "/api/v1/restitute"

[abilities_database]
mongo_database = "oratio"
mongo_collection = "abilities"
mongo_url = "mongodb://localhost:27017"

[abilities_cache]
expiration = "24h"
cleanup_interval = "1h"

[[abilities]]
name = "cinema"
intents = ["LAST_SHOWTIME"]
host = "localhost"
port = 10200

[[abilities]]
name = "shoppinglist"
intents = ["ADD_TO_LIST", "TRIGGER_SHOPPING_LIST"]
host = "localhost"
port = 4444
