[server]
port = 9100
log_level = "<root>=INFO"

[cerebro]
host = "0.0.0.0"
port = 9444

[anima]
host = "0.0.0.0"
port = 9333

[[abilities]]
    name = "cinema"
    intents = ["LAST_SHOWTIME"]
    host = "cinema-ability"
    port = 10200

#[[abilities]]
#    name = "clock"
#    intents = ["GET_TIME"]
#    host = "clock-ability"
#    port = 10300

[[abilities]]
    name = "shoppinglist"
    intents = ["ADD_TO_LIST"]
    host = "shoppinglist-ability"
    port = 10400