[server]
port = 9100
log_level = "<root>=INFO"

[cerebro]
host = "0.0.0.0"
port = 9444

[anima]
host = "0.0.0.0"
port = 9333

[[abilities]]
    name = "cinema"
    intents = ["LAST_SHOWTIME"]
    host = "localhost"
    port = 10200

[[abilities]]
    name = "shoppinglist"
    intents = ["ADD_TO_LIST", "TRIGGER_SHOPPING_LIST"]
    host = "localhost"
    port = 4444
