apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oratio.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "oratio.name" . }}
    helm.sh/chart: {{ include "oratio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  configuration-file: |
    [server]
    port = {{ .Values.containerPort }}
    log_level = "<root>=INFO"

    [cerebro]
    host = "cerebro"
    port = 9444

    [anima]
    host = "anima"
    port = 9333

    [[abilities]]
        name = "cinema"
        intents = ["LAST_SHOWTIME"]
        host = "ability-cinema"
        port = 4444

    #[[abilities]]
    #    name = "clock"
    #    intents = ["GET_TIME"]
    #    host = "ability-clock"
    #    port = 4444

    [[abilities]]
        name = "shoppinglist"
        intents = ["ADD_TO_LIST"]
        host = "ability-shoppinglist"
        port = 4444